# Site settings
title: Random stuff
email: kadek.marek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just random blogging
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kadekm.github.io/" # the base hostname & protocol for your site
twitter_username: MarekKadek
github_username:  KadekM

# Build settings
markdown: kramdown
